force-app/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce-Deployment/force-app/main/default/objects/Environment__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <label>Named Credential</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retrieve__c/Retrieve__c.object-meta.xml
<CustomObject>
    <label>Retrieve</label>
    <nameField>
        <displayFormat>SN-{000000}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retrieves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retrieve__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Retrieves</relationshipLabel>
    <relationshipName>Retrieves</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce-Deployment/force-app/main/default/objects/Retrieve__c/fields/PackageFileContent__c.field-meta.xml
<CustomField>
    <fullName>PackageFileContent__c</fullName>
    <label>PackageFileContent</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EnvironmentTest.cls
@IsTest (isParallel = true)
private class EnvironmentTest {
    
    @IsTest
    private static void getEnvironment_when_exists(){
        Environment__c e = new Environment__c();
        e.name = 'abc';
        e.namedcredential__c = 'abc';
        Insert e;
        Test.startTest();
        Environment envObject = new Environment();
        Environment__c resultEnvironment = envObject.get(e.Id);
        Test.stopTest();
        System.assertEquals('abc', e.NamedCredential__c, 'Named credential did not match');
    }
    
    @IsTest
    private static void getEnvironment_when_not_exists(){
        Environment__c e = new Environment__c();
        e.name = 'abc';
        e.namedcredential__c = 'abc';
        Insert e;
        Retrieve__c retrieveJob = new Retrieve__c();
        retrieveJob.Environment__c = e.Id;
        retrieveJob.PackageFileContent__c = 'Some content';
        Insert retrieveJob;
        Test.startTest();
        Environment envObject = new Environment();
        Environment__c resultEnvironment = envObject.get(retrieveJob.Id);              
        Test.stopTest();
        System.assertEquals(null, resultEnvironment, 'Null is expected');
    }
    
}